// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA62jCuUXOno4HH2iHmuDOGF7Wju98Ly3A',
    appId: '1:976907246014:android:0bdefe9e3b431f09dd81ef',
    messagingSenderId: '976907246014',
    projectId: 'now-mindful-moments',
    storageBucket: 'now-mindful-moments.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGsQwGri056a3_MpV8SdyRLTxDT7L3A_g',
    appId: '1:976907246014:ios:05b895d30bdad929dd81ef',
    messagingSenderId: '976907246014',
    projectId: 'now-mindful-moments',
    storageBucket: 'now-mindful-moments.firebasestorage.app',
    iosBundleId: 'com.paperhuts.now',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGsQwGri056a3_MpV8SdyRLTxDT7L3A_g',
    appId: '1:976907246014:ios:05b895d30bdad929dd81ef',
    messagingSenderId: '976907246014',
    projectId: 'now-mindful-moments',
    storageBucket: 'now-mindful-moments.firebasestorage.app',
    iosBundleId: 'com.paperhuts.now',
  );
}
